# Generated by Django 3.0.4 on 2021-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
