# Generated by Django 3.0.4 on 2021-07-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
