# Generated by Django 3.0.4 on 2021-07-12 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0022_auto_20210712_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderdate_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
