# Generated by Django 3.0.4 on 2021-07-12 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0023_auto_20210712_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderdate_field',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
