# Generated by Django 3.0.4 on 2021-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0024_auto_20210712_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderdate_field',
            field=models.DateTimeField(),
        ),
    ]
