# Generated by Django 3.0.4 on 2021-07-12 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0025_auto_20210712_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderdate_field',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
