# Generated by Django 3.0.4 on 2021-07-12 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0026_auto_20210712_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orderdate_field',
            new_name='orderdate',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordertime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
