# Generated by Django 3.0.4 on 2021-07-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0027_auto_20210712_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orderdate',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ordertime',
            new_name='order_time',
        ),
    ]
