# Generated by Django 3.0.4 on 2021-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0029_auto_20210712_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
