# Generated by Django 3.0.4 on 2021-07-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0030_auto_20210714_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Pending', 'Pending')], default='Pending', max_length=15),
        ),
    ]
