# Generated by Django 3.0.4 on 2021-07-25 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0031_auto_20210722_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderslotdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='orderslottime',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='reports',
            field=models.FileField(default='default.png', upload_to='user_reports'),
        ),
    ]
